CREATE TABLE IF NOT EXISTS brand (
  id INT NOT NULL AUTO_INCREMENT,
  code VARCHAR(10) NOT NULL,
  name VARCHAR(40) NOT NULL,
  supplier VARCHAR(40),
  address VARCHAR(120),
  tel VARCHAR(20),
  fax VARCHAR(20),
  terms VARCHAR (40) NOT NULL,
  currency VARCHAR(10) NOT NULL,
  ex_rate INT NOT NULL,
  add_exp_rate INT NOT NULL,
  credit_days INT NOT NULL,
  stock_level_min INT NOT NULL,
  stock_level_max INT NOT NULL,
  whole_sale_margin NUMERIC(15, 2),
  retail_margin_a NUMERIC(15, 2),
  additional_cost_a NUMERIC(15, 2),
  retail_margin_b NUMERIC(15, 2),
  additional_cost_b NUMERIC(15, 2),
  PRIMARY KEY (id)
);
