CREATE TABLE IF NOT EXISTS debtor (
  id INT NOT NULL AUTO_INCREMENT,
  debtor_code VARCHAR(40) NOT NULL,
  debtor_type VARCHAR(40),
  credit_term SMALLINT DEFAULT 0,
  debtor_name_eng TEXT NOT NULL,
  debtor_name_chi TEXT,
  bill_address_l1 TEXT,
  bill_address_l2 TEXT,
  bill_address_l3 TEXT,
  factory_address_l1 TEXT,
  factory_address_l2 TEXT,
  factory_address_l3 TEXT,
  tel TINYTEXT,
  fax TINYTEXT,
  contact_name_l1 TEXT,
  contact_name_l2 TEXT,
  contact_name_l3 TEXT,
  contact_name_l4 TEXT,
  contact_name_l5 TEXT,
  company_profile_l1 TEXT,
  company_profile_l2 TEXT,
  company_profile_l3 TEXT,
  email TEXT,
  remarks_l1 TEXT,
  remarks_l2 TEXT,
  remarks_l3 TEXT,
  bp_discount DECIMAL(5, 2) DEFAULT 0.00,
  etc_discount DECIMAL(5, 2) DEFAULT 0.00,
  sales_current_period_m DECIMAL(17, 2) DEFAULT 0.00,
  sales_current_period_s DECIMAL(17, 2) DEFAULT 0.00,
  sales_current_period_o DECIMAL(17, 2) DEFAULT 0.00,
  sales_current_period_ttl DECIMAL(17, 2) DEFAULT 0.00,
  sales_prev_period_m DECIMAL(17, 2) DEFAULT 0.00,
  sales_prev_period_s DECIMAL(17, 2) DEFAULT 0.00,
  sales_prev_period_o DECIMAL(17, 2) DEFAULT 0.00,
  sales_prev_period_ttl DECIMAL(17, 2) DEFAULT 0.00,
  sales_ytd_m DECIMAL(17, 2) DEFAULT 0.00,
  sales_ytd_s DECIMAL(17, 2) DEFAULT 0.00,
  sales_ytd_o DECIMAL(17, 2) DEFAULT 0.00,
  sales_ytd_ttl DECIMAL(17, 2) DEFAULT 0.00,
  sales_prev_ytd_m DECIMAL(17, 2) DEFAULT 0.00,
  sales_prev_ytd_s DECIMAL(17, 2) DEFAULT 0.00,
  sales_prev_ytd_o DECIMAL(17, 2) DEFAULT 0.00,
  sales_prev_ytd_ttl DECIMAL(17, 2) DEFAULT 0.00,
  sales_outstanding_m DECIMAL(17, 2) DEFAULT 0.00,
  sales_outstanding_s DECIMAL(17, 2) DEFAULT 0.00,
  sales_outstanding_o DECIMAL(17, 2) DEFAULT 0.00,
  sales_outstanding_ttl DECIMAL(17, 2) DEFAULT 0.00,
  PRIMARY KEY (id)
);
